# 数据库（ECS 内网）
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fresh_express?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: fresh
      password:

# 文件存储（ECS 磁盘）
file:
  storage:
    access-url: http://47.104.195.63:8080
    base-path: /app/upload
    project-path: /FreshExpress

# JWT（生产环境）
fresh:
  jwt:
    admin-secret-key: guinry_prod
    admin-ttl: 72000000
    admin-token-name: token

    user-secret-key: guinry_dev
    user-ttl: 72000000
    user-token-name: authentication
  wechat:
    appid: wxad5c8bd9f0f7a73d
    secret: 3bb2a84bbb26b0a7b2f58384a89ef1b0