# 数据库（本地）
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fresh_express?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: G200410115812
  redis:
    host: localhost
    port: 6379
    database: 10

# 文件存储（本地）
file:
  storage:
    access-path: http://localhost:8080
    base-path: /app/upload
    project-path: /FreshExpress

# JWT（开发环境）
fresh:
  jwt:
    admin-secret-key: guinry_dev
    admin-ttl: 720000000
    admin-token-name: token
